CREATE GLOBAL TEMPORARY TABLE sepo_export_dce
(
  "TPDCE" NUMBER(2,0),
  "IZD" NUMBER(7,0),
  "NAIMD" VARCHAR2(150),
  "DCE" VARCHAR2(18),
  "DATV" DATE,
  "CHNDN" VARCHAR2(30),
  "OKON" VARCHAR2(10),
  "DATAK" DATE,
  "TABV" NUMBER(7,0),
  "TABK" NUMBER(7,0),
  "STATUS" NUMBER(1,0),
  "PRIZN" NUMBER(1,0)
) ON COMMIT PRESERVE ROWS;

ALTER TABLE sepo_export_dce ADD "NIZM" NUMBER(5,0);
ALTER TABLE sepo_export_dce ADD "PVH" VARCHAR2(50);
ALTER TABLE sepo_export_dce ADD "DOP" VARCHAR2(255);
ALTER TABLE sepo_export_dce MODIFY "CHNDN" VARCHAR2(35);
ALTER TABLE sepo_export_dce MODIFY "NIZM" VARCHAR2(10);