SELECT * FROM v$session;

SELECT * FROM dba_directories;

CREATE TABLESPACE omp_db DATAFILE 'E:\ora\oradata\omega\OMP_DB.DBF'
SIZE 100M REUSE AUTOEXTEND ON NEXT 10M;

CREATE TABLESPACE omp_ind DATAFILE 'E:\ora\oradata\omega\OMP_IND.DBF'
SIZE 100M REUSE AUTOEXTEND ON NEXT 10M;

CREATE USER omp_adm IDENTIFIED BY "eastsoft"
DEFAULT TABLESPACE omp_db
TEMPORARY TABLESPACE temp;

GRANT DBA TO omp_adm;

DROP USER omp_adm CASCADE ;